CREATE TABLE USERS(
    USER_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    USER_PASSWORD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    USER_IMAGE VARCHAR2(100) ,
    USER_REGDATE DATE NOT NULL,
    ADMIN_CHECK CHAR(1) NOT NULL
)

CREATE TABLE CATEGORY(
    CATEGORY_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30) NOT NULL
)

CREATE SEQUENCE UC_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100

CREATE TABLE USERCATEGORY(
    UC_ID INT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    CATEGORY_ID VARCHAR2(20) NOT NULL
)

CREATE SEQUENCE FOLLOW_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100

CREATE TABLE FOLLOW(
    FOLLOW_ID INT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    LIKE_ID VARCHAR2(20) NOT NULL
)

CREATE SEQUENCE BOARD_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100
 

CREATE TABLE BOARD(
    BOARD_ID INT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    BOARD_TITLE VARCHAR2(50) NOT NULL,
    BOARD_CONTENT VARCHAR2(300),
    BOARD_REGDATE DATE NOT NULL,
    BOARD_HIT INT NOT NULL,
    BOARD_CHECK INT
)



CREATE SEQUENCE CONTENTS_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100

CREATE TABLE CONTENTS(
    CONTENTS_ID INT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    CATEGORY_ID VARCHAR2(20) NOT NULL,
    CONTENTS_TITLE VARCHAR2(50) NOT NULL,
    CONTENTS_IMAGE1 VARCHAR2(100),
    CONTENTS_IMAGE2 VARCHAR2(100),
    CONTENTS_IMAGE3 VARCHAR2(100),
    CONTENTS_CONTENT VARCHAR2(300),
    CONTENTS_GOALDATE DATE,
    CONTENTS_LOC VARCHAR2(15),
    LAT NUMBER(30),
    LON NUMBER(30),
    CONTENTS_REGDATE DATE NOT NULL,
    CONTENTS_PRIVATE CHAR(1) NOT NULL,
    CONTENTS_COM CHAR(1) NOT NULL
)

CREATE SEQUENCE COMMENTS_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100

CREATE TABLE COMMENTS(
    COMMENTS_ID INT NOT NULL PRIMARY KEY,
    CONTENTS_ID INT,
    USER_ID VARCHAR2(20) NOT NULL,
    COMMENTS_CONTENT VARCHAR2(100) NOT NULL,
    COMMENTS_REGDATE DATE NOT NULL
)

CREATE SEQUENCE FAVORITE_ID
 START WITH 1
 MAXVALUE 999999
 MINVALUE 1
 NOCYCLE
 CACHE 100

CREATE TABLE FAVORITE(
    FAVORITE_ID INT NOT NULL PRIMARY KEY,
    CONTENTS_ID INT NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL
)